name: flutter_blog_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  http: 1.2.2
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  bloc: ^8.1.4
  infinite_scroll_pagination: ^4.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true